config/routes.rb
Prueba::Application.routes.draw do
  resources :comms

  resources :archivos

  resources :comments

  resources :posts

  resources :cursos

  get "registrations_controller/update"

  resources :teachers

  resources :students

  resources :admins

  devise_for :users, :admins, :students, :teachers

  resources :users

match '/comments/new/:id_post' 	=> 'comments#new'
match '/comms/new/:id_comment' 	=> 'comms#new'
match'/comms/create'			=>'comms#create', :as => :comentario_comm
match'/user/passedit/:id'		=>'users#passedit', :as=> :passedit
match'/comment/desactivar/:id' =>'comments#desactivar', :as => :desactivar_comment
match'/comment/activar/:id' =>'comments#activar', :as => :activar_comment
match'/post/desactivar/:id' =>'posts#desactivar', :as => :desactivar_post
match'/post/activar/:id' =>'posts#activar', :as => :activar_post

   root :to => 'static#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to:user
	belongs_to:post
	has_many :comms
	
	validates :content, :presence =>true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	 before_filter :authenticate_user!
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
    @comments = Comment.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @comments }
    end
  end

def desactivar
	com=Comment.find(params[:id])
	post = com.post_id
	com.active=false
	com.save
	
	respond_to do |format|
    
	format.html { redirect_to Post.find(post), :notice => 'Comentario desactivado.' }
        format.json { render :json => com, :status => :created, :location => com }
	end
end

def activar
	com=Comment.find(params[:id])
	post = com.post_id
	com.active=true
	com.save
	
	respond_to do |format|
    
	format.html { redirect_to Post.find(post), :notice => 'Comentario activado.' }
        format.json { render :json => com, :status => :created, :location => com }
	end
end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new
    
	if (!(params[:id_post].nil?))
		@post = Post.find(params[:id_post])
	end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])
    respond_to do |format|
      if @comment.save
	
	@comment.active=true
    @comment.grade2=0
    @comment.save
        format.html { redirect_to Post.find(@comment.post_id), :notice => 'Comentario creado.' }
        format.json { render :json => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.json { render :json => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, :notice => 'Datos actualizados.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    post = @comment.post_id
    
    hijos = Comm.find(:all, :conditions=>{:father_id=>@comment.id})
    
	hijos.each do |hijo|
		nietos = Comm.find(:all, :conditions=>{:father_id=>hijo.son_id})
			nietos.each do |nieto|
				nieeeto = Comment.find(nieto.son_id)
				nieeeto.delete
				nieto.delete
			end
		comentario = Comment.find(hijo.son_id)
		comentario.delete
		hijo.delete
	end    
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to Post.find(post)}
      format.json { head :ok }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
 

<%if current_user.type=="Admin"%>
		<%= f.label :autor %><br />
		<%= f.collection_select(:user_id, User.all, :id, :name) %>
<%else%>
  <div class="field">
    <%= f.label :autor %><br />
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.text_field :user_id, :disabled => "disabled", :value => current_user.name %>
  </div>
  <%end%>
  
 <% if (!(@post.nil?))%>
	<div class="field">
		<%= f.label :Post %><br />
		<%= f.hidden_field :post_id, :value => @post.id %>
		<%= f.text_field :post_id, :disabled => "disabled", :value => @post.title %>
	</div><br>
 <% else %>
	  <div class="field">
		<%= f.label :post %><br />
		<%= f.collection_select(:post_id, Post.all, :id, :title) %>
	  </div>
 <% end %>
 
  <div class="field">
    <%= f.label :contenido %><br />
    <%= f.text_area :content %>
  </div>
  <%if current_user.type =="Admin"%>
  <div class="field">
    <%= f.label :activo %><br />
    <%= f.check_box :active %>
  </div>
  <%end%>
  
  <div class="actions">
    <%= f.submit :Comentar, :confirm=>'No es posible modificar este comentario en el futuro. Continuar? '%>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div id="header">

		<div id="menu">
			<ul>
			<% if user_signed_in? %>
				
				<li><%=link_to "Inicio", root_path%> </span></li>
				<li><%=link_to "Perfil", user_path(current_user)%></li>
					<%if current_user.type=="Admin"%>
					<li><%= link_to "Usuarios", users_path%></li>
					<li><%= link_to "Cursos", cursos_path%></li>
					<li><%= link_to "Posts", posts_path%></li>
					<li class="current_page_item first"><span><%= link_to "Comentarios", comments_path%> </span></li>
					<%end%>
						
				<li><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
				<% else %>
				<li><%=link_to "Inicio", root_path%></li>
				<li><%= link_to "Inscribete", new_user_registration_path %> </li>
				<li><%= link_to "Entra!", new_user_session_path %></li>
				<% end %>
			</ul>
		</div><!-- end #menu -->

</div><!-- end #header -->

<div id="logo">
		<h1>Posts</h1>
		<p>En desarrollo</p>
</div><!-- end #logo -->

<div id="page">

<div id="content">

<h2>Editando Comentario</h2>

<%= render 'form' %>


</div><!-- end #content -->
	<div id="sidebar">
			<ul>
				<li><% if !user_signed_in?%>
					<h2>Entrar</h2>
					<p>
						<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
							<div><%= f.label :email %> </br>
							<%= f.email_field :email %></div>

							<div><%= f.label :password %></br>
							<%= f.password_field :password %></div>

							<% if devise_mapping.rememberable? -%>
							<div><%= f.check_box :remember_me %> <%= f.label "Recordarme" %></div>
							<% end %>

							<div><%= f.submit "Entrar" %></div>
							<% end %>
							
					</p>
					<%end%>
				</li>
				
			</ul>
	</div><!-- end #sidebar -->
	<div style="clear: both;">&nbsp;</div>

	</div>

</div><!-- end #page -->
<div id="footer">

		<p>Copyright (c) 2011 iic2515-3 Cristian Schalper. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>

	</div>

	<!-- end #footer -->

app/views/comments/index.html.erb
<div id="header">

		<div id="menu">
			<ul>
			<% if user_signed_in? %>
				
				<li><%=link_to "Inicio", root_path%></li>
				<li><%=link_to "Perfil", user_path(current_user)%></li>
					
					<%if current_user.type=="Admin"%>
					<li><%= link_to "Usuarios", users_path%></li>
					<li><%= link_to "Cursos", cursos_path%></li>
					<li><%= link_to "Posts", posts_path%></li>
					<li class="current_page_item first"><span><%= link_to "Comentarios", comments_path%> </span></li>
					<%end%>
						
				<li><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
				<% else %>
				<li class="current_page_item first"><span><%=link_to "Inicio", root_path%> </span></li>
				<li><%= link_to "Inscribete", new_user_registration_path %> </li>
				<li><%= link_to "Entra!", new_user_session_path %></li>
				<% end %>
			</ul>
		</div><!-- end #menu -->

</div><!-- end #header -->

<div id="logo">
		<h1>Posts</h1>
		<p>En desarrollo</p>
</div><!-- end #logo -->

<div id="page">

	<div id="content">
<%if current_user.type=="Admin"%>

<h2>Comentarios</h2>
<br>
<table border ="1">
  <tr>
    <th>Autor</th>
    <th>Post</th>
    <th>Fecha de Creacion</th>
    <th>Activo</th>
    <th></th>
    
  </tr>

<% @comments.each do |comment| %>
  <tr align="center">
    <td><%= User.find(comment.user_id).name%> <%= User.find(comment.user_id).lastname%></td>
    <td><%= Post.find(comment.post_id).title %></td>
    <td><%= comment.created_at %></td>
    <td>
     <%if comment.active %>
    Si
    <%else%>
    No
    <%end%></td>
    <td><%= link_to 'Ver', comment %><br>
    <%= link_to 'Editar', edit_comment_path(comment) %><br>
    <%= link_to 'Eliminar', comment, :confirm => 'Alerta! Esto no puede deshacerse. Seguro?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br>
<%=will_paginate @comments%>
<br />

<%= link_to 'Nuevo Comentario', new_comment_path %>

<%else%>
<br>
<b>Lo sentimos, no puedes ver esta parte del sitio web.</b>
<%end%>

</div><!-- end #content -->

		




	<div id="sidebar">
			<ul>
				<li><% if !user_signed_in?%>
					<h2>Entrar</h2>
					<p>
						<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
							<div><%= f.label :email %> </br>
							<%= f.email_field :email %></div>

							<div><%= f.label :password %></br>
							<%= f.password_field :password %></div>

							<% if devise_mapping.rememberable? -%>
							<div><%= f.check_box :remember_me %> <%= f.label "Recordarme" %></div>
							<% end %>

							<div><%= f.submit "Entrar" %></div>
							<% end %>
							
					</p>
					<%end%>
				</li>
				
			</ul>
	</div><!-- end #sidebar -->
	<div style="clear: both;">&nbsp;</div>

	</div>

</div><!-- end #page -->
<div id="footer">

		<p>Copyright (c) 2011 iic2515-3 Cristian Schalper. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>

	</div>

	<!-- end #footer -->

app/views/comments/new.html.erb
<div id="header">

		<div id="menu">
			<ul>
			<% if user_signed_in? %>
				
				<li><%=link_to "Inicio", root_path%> </span></li>
				<li><%=link_to "Perfil", user_path(current_user)%></li>
				
				<%if current_user.type=="Admin"%>
					<li><%= link_to "Usuarios", users_path%></li>
					<li><%= link_to "Cursos", cursos_path%></li>
					<li><%= link_to "Posts", posts_path%></li>
					<li  class="current_page_item first"><span><%= link_to "Comentarios", comments_path%> </span></li>
					<%end%>
					<%if current_user.type=="Teacher"%>
					<%curso = Curso.find(current_user.curso_id) %>
					<li><%= link_to "Mi curso", curso%></li>
					<%end%>
					<%if current_user.type=="Student"%>
					<%cursos = Curso.find(:all, :conditions=>{:id=>current_user.curso_id})%>
					<%cursos.each do |curso|%>
					<li><%= link_to "Mi curso", curso%></li>
					<%end%>
					<%end%>
						
				<li><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
				<% else %>
				<li><%=link_to "Inicio", root_path%></li>
				<li><%= link_to "Inscribete", new_user_registration_path %> </li>
				<li><%= link_to "Entra!", new_user_session_path %></li>
				<% end %>
			</ul>
		</div><!-- end #menu -->

</div><!-- end #header -->

<div id="logo">
		<h1>Posts</h1>
		<p>En desarrollo</p>
</div><!-- end #logo -->

<div id="page">

	<div id="content">

<h2>Nuevo Comentario</h2>

 <% if (!(@post.nil?))%>
<%if current_user.curso_id == User.find(@post.user_id).curso_id || current_user.type=="Admin"%>
<%= render 'form' %>
<%else%>
<br>
<strong>No puedes comentar este post, ya que no es de tu curso.</strong>
<br>
<%end%>
<%end%>

<br>
<%=link_to "Cancelar", post_path(@post)%>
</div><!-- end #content -->
	<div id="sidebar">
			<ul>
				<li><% if !user_signed_in?%>
					<h2>Entrar</h2>
					<p>
						<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
							<div><%= f.label :email %> </br>
							<%= f.email_field :email %></div>

							<div><%= f.label :password %></br>
							<%= f.password_field :password %></div>

							<% if devise_mapping.rememberable? -%>
							<div><%= f.check_box :remember_me %> <%= f.label "Recordarme" %></div>
							<% end %>

							<div><%= f.submit "Entrar" %></div>
							<% end %>
							
					</p>
					<%end%>
				</li>
				
			</ul>
	</div><!-- end #sidebar -->
	<div style="clear: both;">&nbsp;</div>

	</div>

</div><!-- end #page -->
<div id="footer">

		<p>Copyright (c) 2011 iic2515-3 Cristian Schalper. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>

	</div>

	<!-- end #footer -->

app/views/comments/show.html.erb
<div id="header">

		<div id="menu">
			<ul>
				<% if user_signed_in? %>
				<li><%=link_to "Inicio", root_path%> </span></li>
				<li><%=link_to "Perfil", user_path(current_user)%></li>
					<%if current_user.type=="Admin"%>
					<li><%= link_to "Usuarios", users_path%></li>
					<li><%= link_to "Cursos", cursos_path%></li>
					<li><%= link_to "Posts", posts_path%></li>
					<li class="current_page_item first"><span><%= link_to "Comentarios", comments_path%> </span></li>
					<%end%>
					<%if current_user.type=="Teacher"%>
					<%curso = Curso.find(current_user.curso_id) %>
					<li><%= link_to "Mi curso", curso%></li>
					<%end%>
					<%if current_user.type=="Student"%>
					<%cursos = Curso.find(:all, :conditions=>{:id=>current_user.curso_id})%>
					<%cursos.each do |curso|%>
					<li><%= link_to "Mi curso", curso%></li>
					<%end%>
					<%end%>
						
				<li><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
				<% else %>
				<li><%=link_to "Inicio", root_path%></li>
				<li><%= link_to "Inscribete", new_user_registration_path %> </li>
				<li><%= link_to "Entra!", new_user_session_path %></li>
				<% end %>
			</ul>
		</div><!-- end #menu -->

</div><!-- end #header -->

<div id="logo">
		<h1>Posts</h1>
		<p>En desarrollo</p>
</div><!-- end #logo -->

<div id="page">

	<div id="content">

<p>
  <b>Autor:</b>
  <%= User.find(@comment.user_id).name %> <%= User.find(@comment.user_id).lastname %>
</p>

<p>
  <b>Post:</b>
  <%= Post.find(@comment.post_id).title %>
</p>

<p>
  <b>Fecha de creacion:</b><br>
  <%= @comment.created_at %>
</p>

<p>
  <b>Contenido:</b><br>
  <%= @comment.content %>
</p>

<%if current_user.type=="Admin"%>
<%= link_to 'Editar', edit_comment_path(@comment) %> 
<%end%>
</div><!-- end #content -->
	<div id="sidebar">
			<ul>
				<li><% if !user_signed_in?%>
					<h2>Entrar</h2>
					<p>
						<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
							<div><%= f.label :email %> </br>
							<%= f.email_field :email %></div>

							<div><%= f.label :password %></br>
							<%= f.password_field :password %></div>

							<% if devise_mapping.rememberable? -%>
							<div><%= f.check_box :remember_me %> <%= f.label "Recordarme" %></div>
							<% end %>

							<div><%= f.submit "Entrar" %></div>
							<% end %>
							
					</p>
					<%end%>
				</li>
				
			</ul>
	</div><!-- end #sidebar -->
	<div style="clear: both;">&nbsp;</div>

	</div>

</div><!-- end #page -->
<div id="footer">

		<p>Copyright (c) 2011 iic2515-3 Cristian Schalper. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>

	</div>

	<!-- end #footer -->