config/routes.rb
Prueba::Application.routes.draw do
  resources :comms

  resources :archivos

  resources :comments

  resources :posts

  resources :cursos

  get "registrations_controller/update"

  resources :teachers

  resources :students

  resources :admins

  devise_for :users, :admins, :students, :teachers

  resources :users

match '/comments/new/:id_post' 	=> 'comments#new'
match '/comms/new/:id_comment' 	=> 'comms#new'
match'/comms/create'			=>'comms#create', :as => :comentario_comm
match'/user/passedit/:id'		=>'users#passedit', :as=> :passedit
match'/comment/desactivar/:id' =>'comments#desactivar', :as => :desactivar_comment
match'/comment/activar/:id' =>'comments#activar', :as => :activar_comment
match'/post/desactivar/:id' =>'posts#desactivar', :as => :desactivar_post
match'/post/activar/:id' =>'posts#activar', :as => :activar_post

   root :to => 'static#index'

end

app/models/student.rb
class Student < User
	has_many:cursos
	belongs_to:curso
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible  :name, :lastname, :username, :rut, :type, :email, :password, :password_confirmation, :remember_me
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	 before_filter :authenticate_user!
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, :notice => 'Estudiante creado.' }
        format.json { render :json => @student, :status => :created, :location => @student }
      else
        format.html { render :action => "new" }
        format.json { render :json => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
	   
	format.html { redirect_to @student, :notice => 'Datos actualizados.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :ok }
    end
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 </br>
  <div class="field">
    <%= f.label :usuario %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br />
    <%= f.text_field :lastname %>
  </div>
  
  <div class="field">
    <%= f.label :rut %><br />
    <%= f.number_field :rut %>
    
  </div>
  
  <%if current_user.type=="Admin"%><br>
  <div class="field"> 
  <%= f.label :tipo %><br />
  <%@tipos =[nil, 'Student', 'Teacher', 'Admin']%>
  <%= f.select :type, @tipos %>
  </div>
  <%end%>

<div class="field">
<%= f.label :curso_id %><br />
<%= f.collection_select(:curso_id, Curso.all, :id, :name) %> 
</div>

  <div class="actions">
    <%= f.submit "Guardar"%>
  </div>
<% end %>

app/views/students/edit.html.erb
<div id="header">

		<div id="menu">
			<ul>
			<% if user_signed_in? %>
				
				<li><%=link_to "Inicio", root_path%></li>
				<li><%=link_to "Perfil", user_path(current_user)%></li>
					<%if current_user.type=="Admin"%>
					<li><%= link_to "Usuarios", users_path%></li>
					<li><%= link_to "Cursos", cursos_path%></li>
					<li><%= link_to "Posts", posts_path%></li>
					<li><%= link_to "Comentarios", comments_path%></li>
					<%end%>
					<%if current_user.type=="Teacher"%>
					<%cursos = current_user.cursos %>
					<%cursos.each do |curso| %>
					<li><%= link_to "Mi curso", curso%></li>
					<%end%>
					<%end%>
						
				<li><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
				<% else %>
				<li><%=link_to "Inicio", root_path%></li>
				<li><%= link_to "Inscribete", new_user_registration_path %> </li>
				<li><%= link_to "Entra!", new_user_session_path %></li>
				<% end %>
			</ul>
		</div><!-- end #menu -->

</div><!-- end #header -->

<div id="logo">
		<h1>Posts</h1>
		<p>En desarrollo</p>
</div><!-- end #logo -->

<div id="page">

	<div id="content">

<h2>Editar Usuario</h2>

<%= render 'form' %>

<%= link_to 'Cancelar', user_path%>
</div><!-- end #content -->

	<div id="sidebar">
			<ul>
				<li><% if !user_signed_in?%>
					<h2>Entrar</h2>
					<p>
						<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
							<div><%= f.label :email %> </br>
							<%= f.email_field :email %></div>

							<div><%= f.label :password %></br>
							<%= f.password_field :password %></div>

							<% if devise_mapping.rememberable? -%>
							<div><%= f.check_box :remember_me %> <%= f.label "Recordarme" %></div>
							<% end %>

							<div><%= f.submit "Entrar" %></div>
							<% end %>
							
					</p>
					<%end%>
				</li>
				
			</ul>
	</div><!-- end #sidebar -->
	<div style="clear: both;">&nbsp;</div>

	</div>

</div><!-- end #page -->
<div id="footer">

		<p>Copyright (c) 2011 iic2515-3 Cristian Schalper. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>

	</div>

	<!-- end #footer -->

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_user_path(student) %></td>
    <td><%= link_to 'Destroy', student, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

app/views/students/show.html.erb
<div id="header">

		<div id="menu">
			<ul>
			<% if user_signed_in? %>
				
				<li><%=link_to "Inicio", root_path%> </li>
				<li><%=link_to "Perfil", user_path(current_user)%></li>
					<%if current_user.type=="Admin"%>
					<li><%= link_to "Usuarios", users_path%></li>
					<li><%= link_to "Cursos", cursos_path%></li>
					<li><%= link_to "Posts", posts_path%></li>
					<li><%= link_to "Comentarios", comments_path%></li>
					<%end%>
						
				<li><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
				<% else %>
				<li class="current_page_item first"><span><%=link_to "Inicio", root_path%> </span></li>
				<li><%= link_to "Inscribete", new_user_registration_path %> </li>
				<li><%= link_to "Entra!", new_user_session_path %></li>
				<% end %>
			</ul>
		</div><!-- end #menu -->

</div><!-- end #header -->

<div id="logo">
		<h1>Posts</h1>
		<p>En desarrollo</p>
</div><!-- end #logo -->

<div id="page">

	<div id="content">
<p>
  <b>Usuario:</b>
  <%= @student.username %>
</p>

<p>
  <b>Nombre:</b>
  <%= @student.name %>
</p>

<p>
  <b>Apellido:</b>
  <%= @student.lastname %>
</p>

<p>
  <b>Rut:</b>
  <%= @student.rut %>
</p>

<p>
  <b>Curso:</b>
  <%if !@student.curso_id.nil?%>
  <%= Curso.find(@student.curso_id).name %>
  <%end%>
</p>


<%if current_user.type =="Admin"%>
<%= link_to 'Editar', edit_student_path(@user) %> | 
<%= link_to 'Cambiar Clave', passedit_path(@user)%>
<%end%>
	</div><!-- end #content -->
	

	<div id="sidebar">
			<ul>
				<li><% if !user_signed_in?%>
					<h2>Entrar</h2>
					<p>
						<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
							<div><%= f.label :email %> </br>
							<%= f.email_field :email %></div>

							<div><%= f.label :password %></br>
							<%= f.password_field :password %></div>

							<% if devise_mapping.rememberable? -%>
							<div><%= f.check_box :remember_me %> <%= f.label "Recordarme" %></div>
							<% end %>

							<div><%= f.submit "Entrar" %></div>
							<% end %>
							
					</p>
					<%end%>
				</li>
				
			</ul>
	</div><!-- end #sidebar -->
	<div style="clear: both;">&nbsp;</div>

	</div>

</div><!-- end #page -->
<div id="footer">

		<p>Copyright (c) 2011 iic2515-3 Cristian Schalper. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>

	</div>

	<!-- end #footer -->