config/routes.rb
Prueba::Application.routes.draw do
  resources :comms

  resources :archivos

  resources :comments

  resources :posts

  resources :cursos

  get "registrations_controller/update"

  resources :teachers

  resources :students

  resources :admins

  devise_for :users, :admins, :students, :teachers

  resources :users

match '/comments/new/:id_post' 	=> 'comments#new'
match '/comms/new/:id_comment' 	=> 'comms#new'
match'/comms/create'			=>'comms#create', :as => :comentario_comm
match'/user/passedit/:id'		=>'users#passedit', :as=> :passedit
match'/comment/desactivar/:id' =>'comments#desactivar', :as => :desactivar_comment
match'/comment/activar/:id' =>'comments#activar', :as => :activar_comment
match'/post/desactivar/:id' =>'posts#desactivar', :as => :desactivar_post
match'/post/activar/:id' =>'posts#activar', :as => :activar_post

   root :to => 'static#index'

end

app/models/comm.rb
class Comm < ActiveRecord::Base
	belongs_to :comments
end

app/controllers/comms_controller.rb
class CommsController < ApplicationController
	before_filter :authenticate_user!
  # GET /comms
  # GET /comms.json
  def index
    @comms = Comm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @comms }
    end
  end

  # GET /comms/1
  # GET /comms/1.json
  def show
    @comm = Comm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @comm }
    end
  end

  # GET /comms/new
  # GET /comms/new.json
  def new
    @comment = Comment.new
    @com = Comm.new
    @com.father_id = params[:id_comment]
    @com.son_id = Comment.find(params[:id_comment]).post_id
    @com.save
    @comment.active=true
    
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @comm }
    end
  end

  # GET /comms/1/edit
  def edit
    @comm = Comm.find(params[:id])
  end

  # POST /comms
  # POST /comms.json
  def create
@comment = Comment.new(params[:comment])
@comment.grade2=0
@comment.active=true
    respond_to do |format|
      if @comment.save
     
      com = Comm.last
      @comment.post_id = com.son_id
      @comment.save
      
        com.son_id = @comment.id
	com.save
	
	sum=0
	counter=0
	todospadre = Comm.find(:all, :conditions=>{:father_id=>com.father_id})
	todospadre.each do |hijo|
	comentario = Comment.find(hijo.son_id)
	sum += comentario.nota
	counter +=1
	end
	
	if counter>0
	aux = Comment.find(com.father_id)
	aux.grade2 = sum/counter
	aux.save
	end
	
	
        format.html { redirect_to Post.find(@comment.post_id), :notice => 'Comentario creado.' }
        format.json { render :json => @comm, :status => :created, :location => @comm }
      else
        format.html { render :action => "new" }
        format.json { render :json => @comm.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comms/1
  # PUT /comms/1.json
  def update
    @comm = Comm.find(params[:id])

    respond_to do |format|
      if @comm.update_attributes(params[:comm])
        format.html { redirect_to @comm, :notice => 'Comm was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @comm.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comms/1
  # DELETE /comms/1.json
  def destroy
    @comm = Comm.find(params[:id])
    @comm.destroy

    respond_to do |format|
      format.html { redirect_to comms_url }
      format.json { head :ok }
    end
  end
end

app/helpers/comms_helper.rb
module CommsHelper
end

app/views/comms/_form.html.erb
<%= form_for(@comment, :url=> comentario_comm_path) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 

<%if current_user.type=="Admin"%>
<%= f.label :autor %><br />
<%= f.collection_select(:user_id, User.all, :id, :name) %>
<%else%>

  <div class="field">
<%= f.label :autor %><br />
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.text_field :user_id, :disabled => "disabled", :value => current_user.name %>
  </div>
<%end%>
<%@comment.post_id = @post%>
 
  <div class="field">
    <%= f.label :contenido %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :nota %><br />
<%@notas =[1,2,3,4,5,6,7]%>
<%= f.select :nota, @notas %>
	  </div>
  
  <%if current_user.type =="Admin"%>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active%>
  </div>
  <%end%>
  
  <div class="actions">
    <%= f.submit :Comentar, :confirm=>'No es posible modificar este comentario en el futuro. Continuar? '%>
  </div>
<% end %>
<%@comment.post_id = @post_id%>
<%=@comment.post_id%>

app/views/comms/edit.html.erb
<h1>Editing comm</h1>

<%= render 'form' %>

<%= link_to 'Show', @comm %> |
<%= link_to 'Back', comms_path %>

app/views/comms/index.html.erb
<h1>Listing comms</h1>

<table>
  <tr>
    <th>Father</th>
    <th>Son</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comms.each do |comm| %>
  <tr>
    <td><%= comm.father_id %></td>
    <td><%= comm.son_id %></td>
    <td><%= link_to 'Show', comm %></td>
    <td><%= link_to 'Edit', edit_comm_path(comm) %></td>
    <td><%= link_to 'Destroy', comm, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comm', new_comm_path %>

app/views/comms/new.html.erb
<div id="header">

		<div id="menu">
			<ul>
			<% if user_signed_in? %>
				
				<li><%=link_to "Inicio", root_path%> </span></li>
				<li><%=link_to "Perfil", user_path(current_user)%></li>
				
				<%if current_user.type=="Admin"%>
					<li><%= link_to "Usuarios", users_path%></li>
					<li><%= link_to "Cursos", cursos_path%></li>
					<li><%= link_to "Posts", posts_path%></li>
					<li  class="current_page_item first"><span><%= link_to "Comentarios", comments_path%> </span></li>
					<%end%>
					<%if current_user.type=="Teacher"%>
					<%curso = Curso.find(current_user.curso_id) %>
					<li><%= link_to "Mi curso", curso%></li>
					<%end%>
					<%if current_user.type=="Student"%>
					<%cursos = Curso.find(:all, :conditions=>{:id=>current_user.curso_id})%>
					<%cursos.each do |curso|%>
					<li><%= link_to "Mi curso", curso%></li>
					<%end%>
					<%end%>
						
				<li><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
				<% else %>
				<li><%=link_to "Inicio", root_path%></li>
				<li><%= link_to "Inscribete", new_user_registration_path %> </li>
				<li><%= link_to "Entra!", new_user_session_path %></li>
				<% end %>
			</ul>
		</div><!-- end #menu -->

</div><!-- end #header -->

<div id="logo">
		<h1>Posts</h1>
		<p>En desarrollo</p>
</div><!-- end #logo -->

<div id="page">

	<div id="content">

<h2>Nuevo Comentario</h2>

<%= render 'form' %>

</div><!-- end #content -->
	<div id="sidebar">
			<ul>
				<li><% if !user_signed_in?%>
					<h2>Entrar</h2>
					<p>
						<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
							<div><%= f.label :email %> </br>
							<%= f.email_field :email %></div>

							<div><%= f.label :password %></br>
							<%= f.password_field :password %></div>

							<% if devise_mapping.rememberable? -%>
							<div><%= f.check_box :remember_me %> <%= f.label "Recordarme" %></div>
							<% end %>

							<div><%= f.submit "Entrar" %></div>
							<% end %>
							
					</p>
					<%end%>
				</li>
				
			</ul>
	</div><!-- end #sidebar -->
	<div style="clear: both;">&nbsp;</div>

	</div>

</div><!-- end #page -->
<div id="footer">

		<p>Copyright (c) 2011 iic2515-3 Cristian Schalper. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>

	</div>

	<!-- end #footer -->

app/views/comms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Father:</b>
  <%= @comm.father_id %>
</p>

<p>
  <b>Son:</b>
  <%= @comm.son_id %>
</p>


<%= link_to 'Edit', edit_comm_path(@comm) %> |
<%= link_to 'Back', comms_path %>