config/routes.rb
Prueba::Application.routes.draw do
  resources :comms

  resources :archivos

  resources :comments

  resources :posts

  resources :cursos

  get "registrations_controller/update"

  resources :teachers

  resources :students

  resources :admins

  devise_for :users, :admins, :students, :teachers

  resources :users

match '/comments/new/:id_post' 	=> 'comments#new'
match '/comms/new/:id_comment' 	=> 'comms#new'
match'/comms/create'			=>'comms#create', :as => :comentario_comm
match'/user/passedit/:id'		=>'users#passedit', :as=> :passedit
match'/comment/desactivar/:id' =>'comments#desactivar', :as => :desactivar_comment
match'/comment/activar/:id' =>'comments#activar', :as => :activar_comment
match'/post/desactivar/:id' =>'posts#desactivar', :as => :desactivar_post
match'/post/activar/:id' =>'posts#activar', :as => :activar_post

   root :to => 'static#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to:user
	has_many:comments
	has_many:archivos
	
	validates :title, :presence => true
	validates :content, :presence =>true
	
	has_attached_file :image
		
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	 before_filter :authenticate_user!, :except => [:show]
	 helper_method :sort_column, :sort_direction

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @posts = Post.paginate(:page => params[:page], :per_page => 10)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @posts }
    end
  end

def desactivar
	post=Post.find(params[:id])
	post.active=false
	post.save
	
	respond_to do |format|
    
	format.html { redirect_to post, :notice => 'Post desactivado.' }
        format.json { render :json => com, :status => :created, :location => com }
	end
end

def activar
	post=Post.find(params[:id])
	post.active=true
	post.save
	
	respond_to do |format|
    
	format.html { redirect_to post, :notice => 'Post activado.' }
        format.json { render :json => com, :status => :created, :location => com }
	end
end


  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    @post.active=true
    


    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
   
   respond_to do |format|
      if @post.save
        format.html { redirect_to @post, :notice => 'Post creado.' }
        format.json { render :json => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
     respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, :notice => 'Datos actualizados.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @comments = Comment.find(:all, :conditions=>{:post_id=>@post.id})
    @comments.each do |comment|
	    comment.destroy
	    end
    @post.destroy

    respond_to do |format|
      format.html { redirect_to root_path}
      format.json { head :ok }
    end
  end

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
  end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

  

<%if current_user.type =="Admin"%>
<div class="field">
    <%= f.label :autor %><br />
    <%= f.collection_select(:user_id, User.find(:all, :conditions=>{:type=>"Teacher"}), :id, :name)%>
</div>
<%else%>
  <div class="field">
    <%= f.label :autor %><br />
    <%= f.hidden_field :user_id, :value => @post.user_id%>
    <%= f.text_field :user_id, :disabled => "disabled", :value => User.find(@post.user_id).name %>
  </div>
  <%end%>
  [Todos los campos son obligatorios]

  <br>
<br>
  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br />
    <%= f.text_area :content %>
  </div>
  
  <div class="field">
    <%= f.label :activo %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :Archivo %><br />
    <%= f.file_field :image %>
  </div>
    
  <div class="actions">
    <%= f.submit "Guardar" %>
  </div>
<% end %>

app/views/posts/_newform.html.erb
<%= form_for(@post) do |f| %>
  

  <div class="field">
    <%= f.label :autor %><br />
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.text_field :user_id, :disabled => "disabled", :value => current_user.name %>
  </div>
  
  [Todos los campos son obligatorios]

  <br>
<br>
  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br />
    <%= f.text_area :content %>
  </div>
  
  <div class="field">
    <%= f.label :activo %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :Archivo %><br />
    <%= f.file_field :image %>
  </div>
    
  <div class="actions">
    <%= f.submit "Guardar" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div id="header">

		<div id="menu">
			<ul>
			<% if user_signed_in? %>
				
				<li><%=link_to "Inicio", root_path%></li>
				<li><%=link_to "Perfil", user_path(current_user)%></li>
					<%if current_user.type=="Admin"%>
					<li><%= link_to "Usuarios", users_path%></li>
					<li><%= link_to "Cursos", cursos_path%></li>
					<li  class="current_page_item first"><span><%= link_to "Posts", posts_path%> </span></li>
					<li><%= link_to "Comentarios", comments_path%></li>
					<%end%>
					<%if current_user.type=="Teacher"%>
					<%curso = Curso.find(current_user.curso_id) %>
					<li><%= link_to "Mi curso", curso%></li>
					<%end%>
					
						
				<li><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
				<% else %>
				<li><%=link_to "Inicio", root_path%></li>
				<li><%= link_to "Inscribete", new_user_registration_path %> </li>
				<li><%= link_to "Entra!", new_user_session_path %></li>
				<% end %>
			</ul>
		</div><!-- end #menu -->

</div><!-- end #header -->

<div id="logo">
		<h1>Posts</h1>
		<p>En desarrollo</p>
</div><!-- end #logo -->

<div id="page">

<div id="content">
<h2>Editando Post</h2>
<br>
<%= render 'form' %>

<%= link_to 'Cancelar', post_path(@post) %>

	</div><!-- end #content -->




	<div id="sidebar">
			<ul>
				<li><% if !user_signed_in?%>
					<h2>Entrar</h2>
					<p>
						<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
							<div><%= f.label :email %> </br>
							<%= f.email_field :email %></div>

							<div><%= f.label :password %></br>
							<%= f.password_field :password %></div>

							<% if devise_mapping.rememberable? -%>
							<div><%= f.check_box :remember_me %> <%= f.label "Recordarme" %></div>
							<% end %>

							<div><%= f.submit "Entrar" %></div>
							<% end %>
							
					</p>
					<%end%>
				</li>
				
			</ul>
	</div><!-- end #sidebar -->
	<div style="clear: both;">&nbsp;</div>

	</div>

</div><!-- end #page -->
<div id="footer">

		<p>Copyright (c) 2011 iic2515-3 Cristian Schalper. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>

	</div>

	<!-- end #footer -->

app/views/posts/index.html.erb
<div id="header">

		<div id="menu">
			<ul>
			<% if user_signed_in? %>
				
				<li><%=link_to "Inicio", root_path%></li>
				<li><%=link_to "Perfil", user_path(current_user)%></li>
					<%if current_user.type=="Admin"%>
					<li><%= link_to "Usuarios", users_path%></li>
					<li><%= link_to "Cursos", cursos_path%></li>
					<li  class="current_page_item first"><span><%= link_to "Posts", posts_path%> </span></li>
					<li><%= link_to "Comentarios", comments_path%></li>
					<%end%>
						
				<li><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
				<% else %>
				<li class="current_page_item first"><span><%=link_to "Inicio", root_path%> </span></li>
				<li><%= link_to "Inscribete", new_user_registration_path %> </li>
				<li><%= link_to "Entra!", new_user_session_path %></li>
				<% end %>
			</ul>
		</div><!-- end #menu -->

</div><!-- end #header -->

<div id="logo">
		<h1>Posts</h1>
		<p>En desarrollo</p>
</div><!-- end #logo -->

<div id="page">

	<div id="content">

<%if current_user.type=="Admin"%>
<h2>Posts</h2>
<br>

<table border ="1">
  <tr>
    <th>Autor</th>
    <th>Titulo</th>
    <th>Activo</th>
    <th>Fecha Creacion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr align="center">
    <td><%= User.find(post.user_id).name%> <%= User.find(post.user_id).lastname%></td>
    <td><%= post.title %></td>
    <td>
    <%if post.active %>
    Si
    <%else%>
    No
    <%end%>
    </td>
    <td><%= post.created_at %></td>
    <td><%= link_to 'Ver', post %></td>
    <td><%= link_to 'Editar', edit_post_path(post) %></td>
    <td><%= link_to 'Eliminar', post, :confirm => 'Alerta! Esto no puede deshacerse. Seguro?', :method => :delete %></td>
  </tr>
<% end %>

</table>
<br>
<%= will_paginate @posts %>

<br />

<%= link_to 'Nuevo Post', new_post_path %>

<%else%>
<br>
<b>Lo sentimos, no puedes ver esta parte del sitio web.</b>
<%end%>

	</div><!-- end #content -->

		




	<div id="sidebar">
			<ul>
				<li><% if !user_signed_in?%>
					<h2>Entrar</h2>
					<p>
						<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
							<div><%= f.label :email %> </br>
							<%= f.email_field :email %></div>

							<div><%= f.label :password %></br>
							<%= f.password_field :password %></div>

							<% if devise_mapping.rememberable? -%>
							<div><%= f.check_box :remember_me %> <%= f.label "Recordarme" %></div>
							<% end %>

							<div><%= f.submit "Entrar" %></div>
							<% end %>
							
					</p>
					<%end%>
				</li>
				
			</ul>
	</div><!-- end #sidebar -->
	<div style="clear: both;">&nbsp;</div>

	</div>

</div><!-- end #page -->
<div id="footer">

<p>Copyright (c) 2011 iic2515-3 Cristian Schalper. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>

	</div>

	<!-- end #footer -->

app/views/posts/new.html.erb
<div id="header">

		<div id="menu">
			<ul>
			<% if user_signed_in? %>
				
				<li><%=link_to "Inicio", root_path%></li>
				<li><%=link_to "Perfil", user_path(current_user)%></li>
					<%if current_user.type=="Admin"%>
					<li><%= link_to "Usuarios", users_path%></li>
					<li><%= link_to "Cursos", cursos_path%></li>
					<li  class="current_page_item first"><span><%= link_to "Posts", posts_path%> </span></li>
					<li><%= link_to "Comentarios", comments_path%></li>
					<%end%>
					<%if current_user.type=="Teacher"%>
					<%curso = Curso.find(current_user.curso_id) %>
					<li><%= link_to "Mi curso", curso%></li>
					<%end%>
					
						
				<li><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
				<% else %>
				<li><%=link_to "Inicio", root_path%></li>
				<li><%= link_to "Inscribete", new_user_registration_path %> </li>
				<li><%= link_to "Entra!", new_user_session_path %></li>
				<% end %>
			</ul>
		</div><!-- end #menu -->

</div><!-- end #header -->

<div id="logo">
		<h1>Posts</h1>
		<p>En desarrollo</p>
</div><!-- end #logo -->

<div id="page">

<div id="content">

<h2>Nuevo Post</h2>
<br>
<%= render 'newform' %>

<%= link_to 'Cancelar', root_path %>

	</div><!-- end #content -->

	<div id="sidebar">
			<ul>
				<li><% if !user_signed_in?%>
					<h2>Entrar</h2>
					<p>
						<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
							<div><%= f.label :email %> </br>
							<%= f.email_field :email %></div>

							<div><%= f.label :password %></br>
							<%= f.password_field :password %></div>

							<% if devise_mapping.rememberable? -%>
							<div><%= f.check_box :remember_me %> <%= f.label "Recordarme" %></div>
							<% end %>

							<div><%= f.submit "Entrar" %></div>
							<% end %>
							
					</p>
					<%end%>
				</li>
				
			</ul>
	</div><!-- end #sidebar -->
	<div style="clear: both;">&nbsp;</div>

	</div>

</div><!-- end #page -->
<div id="footer">

		<p>Copyright (c) 2011 iic2515-3 Cristian Schalper. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>

	</div>

	<!-- end #footer -->

app/views/posts/show.html.erb
<div id="header">

		<div id="menu">
			<ul>
			<% if user_signed_in? %>
				
				<li><%=link_to "Inicio", root_path%></li>
				<li><%=link_to "Perfil", user_path(current_user)%></li>
					<%if current_user.type=="Admin"%>
					<li><%= link_to "Usuarios", users_path%></li>
					<li><%= link_to "Cursos", cursos_path%></li>
					<li  class="current_page_item first"><span><%= link_to "Posts", posts_path%> </span></li>
					<li><%= link_to "Comentarios", comments_path%></li>
					<%end%>
					<%if current_user.type=="Teacher"%>
					<%curso = Curso.find(current_user.curso_id) %>
					<li><%= link_to "Mi curso", curso%></li>
					<%end%>
					
					<%if current_user.type=="Student"%>
					<%cursos = Curso.find(:all, :conditions=>{:id=>current_user.curso_id})%>
					<%cursos.each do |curso|%>
					<li><%= link_to "Mi curso", curso%></li>
					<%end%>
					<%end%>
						
				
				<li><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
				<% else %>
				<li><%=link_to "Inicio", root_path%></li>
				<li><%= link_to "Inscribete", new_user_registration_path %> </li>
				<li><%= link_to "Entra!", new_user_session_path %></li>
				<% end %>
			</ul>
		</div><!-- end #menu -->

</div><!-- end #header -->

<div id="logo">
		<h1>Posts</h1>
		<p>En desarrollo</p>
</div><!-- end #logo -->

<div id="page">

<div id="content">

<div class="post">

				<h2 class="title"><%= @post.title %></h2>

				<p class="meta"><%= @post.created_at %><span> - Autor:   <%= User.find(@post.user_id).name%> <%= User.find(@post.user_id).lastname %>
				
				<%if current_user.type=="Admin" ||current_user.type=="Teacher" %>
				<%if @post.active %><strong> - Post activo</strong> <i><%= link_to "[Desactivar]", desactivar_post_path(@post)%></i>
				<%else%><strong> - Post inactivo</strong> <i><%= link_to "[Activar]", activar_post_path(@post)%></i>
				<%end%>
				<i><%= link_to '[Eliminar]', @post, :confirm => 'Alerta! Esto no puede deshacerse. Seguro?', :method => :delete %></i>
				</span></p>
				<%end%>

				<div class="entry">

					<p> <%= @post.content %></p>
				</div>

</div>

<p>
  
</p>
<p>
<%if !current_user.nil?%>
<%if current_user.type=="Admin"|| current_user.curso_id == User.find(@post.user_id).curso_id%>
<%if !@post.image_file_name.nil?%>
<b>Archivo adjunto: </b>
<%= link_to "Descargar", @post.image.url %>
</p>
<%end%>
<%end%>
<%end%>
<p>
<br>
  <b>Comentarios:</b>
<%comments = Comment.find(:all, :conditions=>{:post_id=>@post.id})%>
  
  <%comments.each do |comment|%>

	  <%if comment.active || current_user.type=="Admin" || current_user.type=="Teacher" %>
	  <div>
		  <br>
		  <u>Autor</u>: <%=User.find(comment.user_id).name%> <%=User.find(comment.user_id).lastname%>  <u>Fecha</u>: <%=comment.created_at%>
		  
		 <%if current_user.type=="Admin" ||current_user.type=="Teacher" %>
		 <%if comment.active %><strong> - Comentario activo</strong> <br> <i><%= link_to "[Desactivar]", desactivar_comment_path(comment)%></i>
		 <%else%> <strong> - Comentario inactivo</strong> <br>  <i><%= link_to "[Activar]", activar_comment_path(comment)%></i>
		 <%end%>
		 <i><%= link_to '[Eliminar]', comment, :confirm => 'Alerta! Esto no puede deshacerse. Seguro?', :method => :delete %></i>

		 <%end%>
		 
		  </br>
		 <%if comment.grade2>0%>
		 <i>Promedio: <%=comment.grade2%></i></br>
		 <%end%>
		 
		 <br><br>
		  <%=comment.content%></br>
		  <%if !current_user.nil?%>
		  <%if current_user.type=="Admin"|| current_user.curso_id == User.find(@post.user_id).curso_id%>
		  <div align = "center"><%= link_to 'Comentar comentario', new_comm_path+'/' + comment.id.to_s%><br></div>
		  
		  <%end%>
		  <%end%>
		  -------------------------------------------------------------------------- 
	   </div>
		 
		  <%hijoss = Comm.find(:all, :conditions=>{:father_id=>comment.id})%>
		 
		 <%if hijoss.count ==0%>
		 <%else%>
			 <%i = hijoss.count%>
			 <%hijos=[]%>
				 <%while i>0 do %>
				 <%hijos[i-1]=Comment.find(hijoss[i-1].son_id)%>
				 <%i = i -1%>
				 <%end%>
				 
			 <%hijos.each do |hijo|%>
				<%comments.delete(hijo)%>
				 <%if hijo.active  || current_user.type=="Admin" || current_user.type=="Teacher"%>
				 <div id="hijo">
					  <br>
					  <u>Autor</u>: <%=User.find(hijo.user_id).name%> <%=User.find(hijo.user_id).lastname%>  <u>Fecha</u>: <%=hijo.created_at%>
						<%if current_user.type=="Admin" ||current_user.type=="Teacher" %>
						<%if hijo.active %><strong> - Comentario activo</strong> <br> <i><%= link_to "[Desactivar]", desactivar_comment_path(hijo)%></i>
						<%else%> <strong> - Comentario inactivo</strong><br>   <i><%= link_to "[Activar]", activar_comment_path(hijo)%></i>
						<%end%>
						<i><%= link_to '[Eliminar]', hijo, :confirm => 'Alerta! Esto no puede deshacerse. Seguro?', :method => :delete %></i>

						<%end%>
					  
					  
					  </br>
					 <%if hijo.grade2>0%>
						<i>Promedio: <%=hijo.grade2%></i>
					<%end%>
					<i> Nota entregada: <%=hijo.nota%></i></br>
					 <br><br>
					 <%=hijo.content%></br>
					<%if !current_user.nil?%>
						<%if current_user.type=="Admin"|| current_user.curso_id == User.find(@post.user_id).curso_id%>
						<div align = "center"><%= link_to 'Comentar comentario', new_comm_path+'/' + hijo.id.to_s%><br></div>
						<%end%>
					  <%end%>
					  --------------------------------------------------------------------------
				</div>
				<%i+=1%>
					 
					 
					 <%hijoss2 = Comm.find(:all, :conditions=>{:father_id=>hijo.id})%>
					 
					 <%if hijoss2.count==0%>
					<%else%>
						<%hijos2 = []%>
						<%i = hijoss2.count%>
							 <%while i>0 do %>
							 <%hijos2[i-1]= Comment.find(hijoss2[i-1].son_id)%>
							 <%i = i -1%>
							 <%end%>
						 <%hijos2.each do |nieto|%>
						 <%comments.delete(nieto)%>
							 <%if nieto.active  || current_user.type=="Admin"|| current_user.type=="Teacher"%>
							<div id ="nieto">
							  <br>
							  <u>Autor</u>: <%=User.find(nieto.user_id).name%> <%=User.find(nieto.user_id).lastname%>  <u>Fecha</u>: <%=nieto.created_at%>
							  <%if current_user.type=="Admin" ||current_user.type=="Teacher" %>
								<%if nieto.active %><strong> - Comentario activo</strong><br>  <i><%= link_to "[Desactivar]", desactivar_comment_path(nieto)%></i>
								<%else%> <strong> - Comentario inactivo</strong><br>   <i><%= link_to "[Activar]", activar_comment_path(nieto)%></i>
								<%end%>
								<i><%= link_to '[Eliminar]', nieto, :confirm => 'Alerta! Esto no puede deshacerse. Seguro?', :method => :delete %></i>

								<%end%>
							  
							  </br>
							 <%if nieto.grade2>0%>
							<i>Promedio: <%=nieto.grade2%></i>
							<%end%>  -  <i> Nota entregada: <%=nieto.nota%></i></br>
							 <br><br>
							  <%=nieto.content%></br>
							  --------------------------------------------------------------------------
							  </div>
						
							 <%end%>
						 <%end%> 
					 <%end%>
				 <%end%>
			 <%end%>
		 <%end%>
	 <%end%>
 <%end%>
  
  

  
  
  
  <br>
  <% if user_signed_in? %>
  <%if current_user.type=="Admin"|| current_user.curso_id == User.find(@post.user_id).curso_id%>
  <br>
  <%=link_to 'Comentar Post', new_comment_path + '/' + @post.id.to_s%>
  <%end%>
  
</p>


<%if current_user.id == @post.user_id || current_user.type=="Admin"%>
<%= link_to 'Editar', edit_post_path(@post) %> 
<%end%>
<%end%>

	</div><!-- end #content -->

	<div id="sidebar">
			<ul>
				<li><% if !user_signed_in?%>
					<h2>Entrar</h2>
					<p>
						<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
							 <div><%= f.label "E-mail, Rut o Usuario" %><br />
							  <%= f.text_field :login %></div>
							  
							  <div>Contrase&ntilde;a</br>
							<%= f.password_field :password %></div>

							<% if devise_mapping.rememberable? -%>
							<div><%= f.check_box :remember_me %> <%= f.label "Recordarme" %></div>
							<% end %>

							<div><%= f.submit "Entrar" %></div>
							<% end %>
							
					</p>
					<%end%>
				</li>
				
			</ul>
	</div><!-- end #sidebar -->
	<div style="clear: both;">&nbsp;</div>

	</div>

</div><!-- end #page -->
<div id="footer">

		<p>Copyright (c) 2011 iic2515-3 Cristian Schalper. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>

	</div>

	<!-- end #footer -->